defaults: &defaults
  adapter: mysql
  username: root
  password:

development:
  <<: *defaults
  database: r4rmusic_development

test:
  <<: *defaults
  database: r4rmusic_test

production:
  <<: *defaults
  database: r4rmusic_production